CREATE TABLE MENU (
  ID       INT          NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME     VARCHAR(255) NOT NULL,
  PRICE    DOUBLE       NOT NULL,
  WEIGHT   DOUBLE       NOT NULL,
  DISCOUNT BOOLEAN      NOT NULL
);